### ISSUE TITLE
How much DigitalOcean droplets for Mongo Sharding?

### ISSUE THREAD

**Issue by thearabbit** [justmeandopensource/learn-mongodb#2]
The first, thanks for your tutorial.
I would like to try `Mongo Sharding` on DigitalOcean droplets.
- How many `Droplets`, we need for `2 Shardings`?
- How Droplets size: Ram, CPU...?
- How many database that we could created: one, two, three..

**Comment by justmeandopensource** [comment]
HI Theara, 
I don't monitor github issues. For any questions/issues, please use YouTube chat section in the appropriate videos so that other viewers can also benefit from the discussion.
Thanks.
