### ISSUE TITLE
cannot connect to mongo instance commnad is not working

### ISSUE THREAD

**Issue by lisawebcoder** [justmeandopensource/learn-mongodb#5]
hello i tried for 3 days but your command is missing somtheing
mongo mongodb IP address/:40001
it does not work 
to me this syntax is wrong
soince i have dome replica sets and sharding w/out docker containers and it works

plz advise but its not working in your docker mongo shard vids

thxz anyway and thxz

Lisa

**Comment by lisawebcoder** [comment]
also if you do ofind the correct syntax to deply in docker container would you know how to deploy on 3 physical macnies as aopposed to one machine with ddiffernet ports?
this is the real production method on how it really worlks for real service to customers

thxz alot 

Lisa

**Comment by lisawebcoder** [comment]
hello instead of mongo mongodb://192.168.1.81:40001 to connect to a mongo instance , only this work ed for me so far, docker exec -it cfgsvr1 mongo
is it the same effect? Lisa
 
rs.initiate(
 {
    _id: "cfgrs",
    configsvr: true,
    members: [
      { _id : 0, host : "localhost:40001" },
      { _id : 1, host : "localhost:40002" },
      { _id : 2, host : "localhost:40003" }
    ]
  }
)

 "errmsg" : "No host described in new configuration 1 for replica set cfgrs maps to this node",
        "code" : 93,
        "codeName" : "InvalidReplicaSetConfig",

**Comment by lisawebcoder** [comment]
rs.initiate(
{
_id: "cfgrs",
configsvr: true,
members: [
{ _id : 0, host : "27017:40001" },
{ _id : 1, host : "27017:40002" },
{ _id : 2, host : "27017:40003" }
]
}
)


this doesnt work either



rs.initiate(
{
_id: "cfgrs",
configsvr: true,
members: [
{ _id : 0, host : "127.0.0.1:40001" },
{ _id : 1, host : "127.0.0.1:40002" },
{ _id : 2, host : "127.0.0.1:40003" }
]
}
)

neither does this work

"errmsg" : "No host described in new configuration 1 for replica set cfgrs maps to this node",
"code" : 93,
"codeName" : "InvalidReplicaSetConfig",

hello is anyone there?
thxz
Lisa

**Comment by lisawebcoder** [comment]
config = {
  "_id": "cfgrs",
  "members": [
    {
      "_id": 0,
      "host": "cfgsvr1:27017"
    },
    {
      "_id": 1,
      "host": "cfgsvr2:27017"
    },
    {
      "_id": 2,
      "host": "cfgsvr3:27017"
    }
  ]
}

this worked so far

**Comment by lisawebcoder** [comment]
then thsi
rs.initiate(config)

and i am on secondary but press enter and i am on primary

then open 2 more cmd pr PS prompts on Windows machine and enter on each prompt
docker exec -it cfgsvr2 mongo
docker exec -it cfgsvr3 mongo
these are secondaries

so now its complete but i am still need to follwo sharding steps yaml files
will those files work or i need to research configuration like i just did so far?
\thxz
Lisa

**Comment by lisawebcoder** [comment]
docker-compose -f shard1/docker-compose.yaml up -d

mongo mongodb://192.168.1.81:50001 replace with
docker exec -it shard1svr1 mongo
and then
config = {
"_id": "shard1rs",
"members": [
{
"_id": 0,
"host": "shard1svr1:27017"
},
{
"_id": 1,
"host": "shard1svr2:27017"
},
{
"_id": 2,
"host": "shard1svr3:27017"
}
]
}
then thsi
rs.initiate(config)
rs.status()

**Comment by lisawebcoder** [comment]
i changed mongos yaml docker file like so 
i dont know if it will work
docker-compose -f mongos/docker-compose.yaml up -d

version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/cfgsvr1:40001,cfgsvr2:40002,cfgsvr3:40003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017

**Comment by lisawebcoder** [comment]
not sure if my previous script worked it keeps saying not connecting
but anyway then this line
mongo mongodb://192.168.1.81:60000
replace with
docker exec -it mongos mongo
but it fails also
i dont know why

**Comment by lisawebcoder** [comment]
i changed mongos yaml file to this

version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017

but still doesnt work

**Comment by lisawebcoder** [comment]
hello i had to merge commands from another lesson with this lesson and then i finally complete it as per this link below, when i clean it up i will post it here but it works

https://dzone.com/articles/composing-a-sharded-mongodb-on-docker

**Comment by justmeandopensource** [comment]
Hi Lisa,
I just verified it and it worked perfectly fine as shown in the accompanied YouTube video. This was tested on a Linux machine. It may be that your issue is specific to your Windows environment.
